module.exports = {
    page_size : 20,
    page_number : 0,
    followPageSize : 50,
    postPageSize : 50,

    // Success message
    PASSWORD_CHANGED_SUCCESS : "Password Changed Successfully",
    Name_REQ : "Name is required",
    USER_CREATED_SUCCESS : "User Created Successfully",
    AUTH_SUCCESS : "Successfully authenticated",
    LOGOUT_SUCCESS : "Logout Successfully",
    VERIFICATION_CODE_SUCCESS : "Verification code added successfully",
    VALID_MOBILE : "Mobile is valid",
    OTP_SENT: "OTP Sent",
    VERIFIED_SUCCESS : "Verified successfully",
    SUCCESS : "Success",
    USER_UPDATED_SUCCESS: "User detail updated successfully",
    UNFOLLOW_SUCCESS : "Unfollow successfully",
    FOLLOW_SUCCESS : "Follow successfully",
    POST_ADDED_SUCCESS: "Post added successfully",
    POST_DELETED_SUCCESS : "Post deleted successfully",
    POST_LIKE_SUCCESS : "Post like successfully",
    POST_UNLIKE_SUCCESS : "Post unlike successfully",
    POST_UPDATED_SUCCESS :"Post updated successfully",
    COMMENT_ADDED_SUCCESS : "Comment added successfully",
    EMAIL_SENT_SUCCESS : "Email sent successfully",
    POST_SHARED_SUCCESS:"Post shared successfully",
    ADDED_POST_IN_PLAYLIST_SUCCESS : "Post has been added successfully in playlist",
    REMOVED_POST_FROM_PLAYLIST_SUCCESS : "Post has been removed successfully from playlist",
    USER_BLOCKED_SUCCCESS : "User has been blocked successfully",
    USER_UNBLOCKED_SUCCCESS : "User has been unblocked successfully",
    QUICK_BLOX_ID_UPDATED_SUCCESS:"Quickblox id updated successfully",

    // Validation message
    WRONG_PASSWORD : "Wrong password",
    USER_NOT_EXIST : "User name does not exist",
    USER_ALREADY_EXIST : "Username has already been taken",
    EMAIL_ALREADY_EXIST : "Email already exist",
    OLD_PASSWORD_WRONG : "Old password is wrong",
    INVALID_USERID : "Invalid userId",
    MOBILE_ALREADY_VERIFIED : "Mobile already verified for another account",
    NOT_AUTHORIZED_USER : "Not Authorized",
    WRONG_VERIFICATION_CODE : "Wrong verification code",
    INVALID_USER : "Invalid User",
    USER_NOT_VERIFIED : "User not verified",
    MOBILE_ALREADY_EXIST : "Mobile number already exist",
    FOLLOW_LOGIN_USER_HIMSELF : "Login user can not follow own",
    INVALID_POST_ID : "Invalid post id",
    ANOTHER_USER_POST_DELETE_VALIDATION : "You can not delete another user post",
    NOT_UPDATE_ANOTHER_POST:"You can not update another user post",
    EMAIL_NOT_VALID : "Invalid email",
    EMAIL_NOT_FOUND : "Email not exist",
    PASSWORD_VALIDATION:"Password must contain atleast 8 characters, including UPPER,lower case, number and symbol",

    // Required field message
    USER_NAME_REQ : "username required",
    PASSWORD_REQ : "password required",
    EMAIL_REQ : "email required",
    USER_ID_REQ : "user Id required",
    OLD_PASSWORD_REQ : "Old password required",
    NEW_PASSWORD_REQ : "New password required",
    VERIFICATION_CODE_REQ : "verification code required",
    MOBILE_REQ : "Mobile required",
    VERIFICATION_TYPE_REQ : "Verification type required",
    VERIFICATION_VALUE_REQ : "Verification value required",
    QUESTION_ID_REQ : "Question id required",
    ANSWER_REQ : "Answer required",
    FOLLOWING_USER_ID_REQ : "Following user id required",
    GAMENAME_REQ:"Game name required",
    PLATFORM_REQ:"Platform required",
    POST_LINK_REQ : "Post link required",
    POST_TYPE_REQ : "Post type required and type must be 'video' or 'image'",
    POST_TYPE_VAL_REQ : "Invalid post type. Post type must be 'video' or 'image'",
    GENRE_REQ : "Genre required",
    POSTID_REQ : "Post id required",
    COMMENT_REQ : "Comment required",
    BLOCK_USER_ID_REQ : "Block user id required",
    CATEGORY_TYPE_REQ: "Category type required",
    CATEGORY_VALUE_REQ : "Category value required",
    HASHTAG_VALUE_REQ: "Hashtag value required",
    QUICK_BLOX_ID_REQ: "Quickblox id required",
    GENRE_REQ: "Genre required",
    FILE_NAME_REQ: "File name required",
    FILE_BODY_REQ: "File is required",
    POST_IMG_REQ: "Post image required",
    THUMB_IMG_REQ: "Thumbnail image required",
    COMMENT_ID_REQ: "Comment ID required",
    COMMENT_REPLY_REQ: "Comment reply required",
    INVALID_SOCIAL_LOGIN_TYPE: "Invalid social login type",
    LIKE_STATUS_REQ: "Like status required",
    INVALID_LIKE_STATUS: "Invalid like status"
}